# Generated by Django 4.2 on 2023-05-15 19:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.validate_image_file_extension], verbose_name='avatar')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='surname')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона в формате: '+ХХХХХХХХХХ'. Максимальная длина 15 цифр", regex='^\\+?[0-9]{9,15}$')], verbose_name='phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'users profile',
            },
        ),
    ]
