# Generated by Django 4.2 on 2023-06-01 16:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(blank=True, choices=[(0, 'Кот'), (1, 'Собака')], null=True, verbose_name='animal type')),
                ('sex', models.PositiveIntegerField(blank=True, choices=[(0, 'М'), (1, 'Ж')], null=True, verbose_name='sex type')),
                ('breed', models.CharField(blank=True, max_length=255, null=True, verbose_name='breed')),
                ('color', models.PositiveIntegerField(blank=True, choices=[(0, 'Черный'), (1, 'Коричневый'), (2, 'Светло-коричневый'), (3, 'Рыжий'), (4, 'Белый'), (5, 'Белый-пятнистый'), (6, 'Черный-пятнистый')], null=True, verbose_name='color type')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/', validators=[django.core.validators.validate_image_file_extension], verbose_name='photo')),
                ('pet_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pet user profile',
                'verbose_name_plural': 'pets users profile',
            },
        ),
    ]
