# Generated by Django 4.2 on 2025-05-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_register', '0002_petuserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petuserprofile',
            name='pet_name',
        ),
    ]
