# Generated by Django 4.2 on 2025-05-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_register', '0003_remove_petuserprofile_pet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petuserprofile',
            name='type',
            field=models.PositiveIntegerField(blank=True, choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('bird', 'Птица'), ('rodent', 'Грызун'), ('rabbit', 'Кролик'), ('reptile', 'Рептилия'), ('other', 'Другое животное')], null=True, verbose_name='animal type'),
        ),
    ]
