# Generated by Django 4.2 on 2023-06-12 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('photo', models.ImageField(upload_to='advertisements/', verbose_name='Фото')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона в формате: '+ХХХХХХХХХХ'. Максимальная длина 15 цифр", regex='^\\+?[0-9]{9,15}$')], verbose_name='phone')),
                ('breed', models.CharField(max_length=255, verbose_name='Порода')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('sex', models.CharField(max_length=255, verbose_name='Пол')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-id'],
            },
        ),
    ]
