# Generated by Django 4.2 on 2023-06-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='social_media',
            field=models.URLField(blank=True, null=True, verbose_name='Социальные сети'),
        ),
    ]
