# Generated by Django 4.2 on 2025-05-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='eye_color',
            field=models.CharField(choices=[('blue', 'Голубые'), ('green', 'Зеленые'), ('yellow', 'Желтые'), ('brown', 'Карие'), ('different', 'Разные')], default='yellow', max_length=20, verbose_name='Цвет глаз'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='face_shape',
            field=models.CharField(choices=[('round', 'Круглая'), ('oval', 'Овальная'), ('triangular', 'Треугольная'), ('long', 'Вытянутая')], default='round', max_length=20, verbose_name='Форма мордочки'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='special_features',
            field=models.CharField(choices=[('heterochromia', 'Гетерохромия'), ('ear_fold', 'Залом на ухе'), ('eye_spot', 'Пятно на глазу'), ('none', 'Нет особых примет')], default='none', max_length=20, verbose_name='Особые приметы'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='color',
            field=models.CharField(choices=[('white', 'Белый'), ('black', 'Черный'), ('gray', 'Серый'), ('brown', 'Коричневый'), ('red', 'Рыжий'), ('multicolor', 'Многоцветный')], default='white', max_length=20, verbose_name='Цвет шерсти'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='sex',
            field=models.CharField(choices=[('male', 'Мальчик'), ('female', 'Девочка'), ('unknown', 'Неизвестно')], default='unknown', max_length=10, verbose_name='Пол'),
        ),
    ]
