# Generated by Django 4.2 on 2025-05-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisement_eye_color_advertisement_face_shape_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='color',
            field=models.CharField(choices=[('white', 'Белый'), ('black', 'Черный'), ('gray', 'Серый'), ('brown', 'Коричневый'), ('red', 'Рыжий'), ('yellow', 'Желтый'), ('green', 'Зеленый'), ('blue', 'Голубой'), ('multicolor', 'Многоцветный')], default='white', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='eye_color',
            field=models.CharField(choices=[('blue', 'Голубые'), ('green', 'Зеленые'), ('yellow', 'Желтые'), ('brown', 'Карие'), ('black', 'Черные'), ('red', 'Красные'), ('different', 'Разные')], default='yellow', max_length=20, verbose_name='Цвет глаз'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='face_shape',
            field=models.CharField(choices=[('round', 'Круглая'), ('oval', 'Овальная'), ('triangular', 'Треугольная'), ('long', 'Вытянутая'), ('flat', 'Плоская'), ('other', 'Другая')], default='round', max_length=20, verbose_name='Форма мордочки'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='special_features',
            field=models.CharField(choices=[('heterochromia', 'Гетерохромия'), ('ear_fold', 'Залом на ухе'), ('eye_spot', 'Пятно на глазу'), ('tail_missing', 'Отсутствует хвост'), ('limb_missing', 'Отсутствует лапка'), ('albino', 'Альбинизм'), ('vitiligo', 'Витилиго'), ('none', 'Нет особых примет')], default='none', max_length=20, verbose_name='Особые приметы'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='type',
            field=models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('bird', 'Птица'), ('rodent', 'Грызун'), ('rabbit', 'Кролик'), ('reptile', 'Рептилия'), ('other', 'Другое животное')], default='cat', max_length=20, verbose_name='Тип животного'),
        ),
    ]
