# Generated by Django 4.2 on 2025-05-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_alter_advertisement_options_advertisement_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ai_analyzed',
            field=models.BooleanField(default=False, help_text='Отмечается автоматически при анализе фото', verbose_name='Проанализировано ИИ'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ai_confidence',
            field=models.FloatField(blank=True, help_text='Общая уверенность ИИ в анализе (0.0-1.0)', null=True, verbose_name='Уверенность ИИ'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='body_proportions',
            field=models.FloatField(blank=True, help_text='Соотношение ширины к высоте', null=True, verbose_name='Пропорции тела'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='body_type',
            field=models.CharField(blank=True, choices=[('compact', 'Компактное'), ('normal', 'Нормальное'), ('elongated', 'Вытянутое'), ('muscular', 'Мускулистое'), ('slim', 'Стройное')], default='normal', max_length=20, null=True, verbose_name='Тип телосложения'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='coat_type',
            field=models.CharField(blank=True, choices=[('short', 'Короткошерстный'), ('medium', 'Среднешерстный'), ('long', 'Длинношерстный'), ('curly', 'Кудрявый'), ('wire', 'Жесткошерстный'), ('hairless', 'Бесшерстный')], default='short', max_length=20, null=True, verbose_name='Тип шерсти'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='color_diversity',
            field=models.IntegerField(blank=True, help_text='Количество основных цветов в окрасе', null=True, verbose_name='Разнообразие цветов'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='estimated_age',
            field=models.CharField(blank=True, help_text='Например: щенок, молодой, взрослый, пожилой', max_length=50, null=True, verbose_name='Примерный возраст'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='fluffiness_score',
            field=models.FloatField(blank=True, help_text='От 0.0 до 1.0, определяется автоматически', null=True, verbose_name='Коэффициент пушистости'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='pattern_complexity',
            field=models.FloatField(blank=True, help_text='Числовое значение, определяется автоматически', null=True, verbose_name='Сложность узора'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='size',
            field=models.CharField(blank=True, choices=[('tiny', 'Очень маленький'), ('small', 'Маленький'), ('medium', 'Средний'), ('large', 'Большой'), ('extra_large', 'Очень большой')], default='medium', max_length=20, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='symmetry_score',
            field=models.FloatField(blank=True, help_text='От 0.0 до 1.0, определяется автоматически', null=True, verbose_name='Коэффициент симметрии'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='temperament',
            field=models.CharField(blank=True, help_text='Например: спокойный, игривый, агрессивный', max_length=100, null=True, verbose_name='Характер'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='weight_estimate',
            field=models.CharField(blank=True, help_text='Например: до 5кг, 5-15кг, 15-30кг, более 30кг', max_length=50, null=True, verbose_name='Примерный вес'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='color',
            field=models.CharField(choices=[('white', 'Белый'), ('black', 'Черный'), ('gray', 'Серый'), ('light_gray', 'Светло-серый'), ('dark_gray', 'Темно-серый'), ('brown', 'Коричневый'), ('red', 'Рыжий'), ('orange', 'Оранжевый'), ('yellow', 'Желтый'), ('golden', 'Золотистый'), ('green', 'Зеленый'), ('blue', 'Голубой'), ('purple', 'Фиолетовый'), ('multicolor', 'Многоцветный'), ('spotted', 'Пятнистый'), ('striped', 'Полосатый'), ('tuxedo', 'Смокинг')], default='white', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='eye_color',
            field=models.CharField(choices=[('blue', 'Голубые'), ('green', 'Зеленые'), ('yellow', 'Желтые'), ('brown', 'Карие'), ('black', 'Черные'), ('red', 'Красные'), ('different', 'Разные'), ('amber', 'Янтарные'), ('hazel', 'Ореховые')], default='yellow', max_length=20, verbose_name='Цвет глаз'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='face_shape',
            field=models.CharField(choices=[('round', 'Круглая'), ('oval', 'Овальная'), ('triangular', 'Треугольная'), ('long', 'Вытянутая'), ('flat', 'Плоская'), ('square', 'Квадратная'), ('other', 'Другая')], default='round', max_length=20, verbose_name='Форма мордочки'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='special_features',
            field=models.CharField(choices=[('heterochromia', 'Гетерохромия'), ('ear_fold', 'Залом на ухе'), ('eye_spot', 'Пятно на глазу'), ('tail_missing', 'Отсутствует хвост'), ('limb_missing', 'Отсутствует лапка'), ('albino', 'Альбинизм'), ('vitiligo', 'Витилиго'), ('spotted_pattern', 'Пятнистый узор'), ('striped_pattern', 'Полосатый узор'), ('fluffy_coat', 'Пушистая шерсть'), ('curly_coat', 'Кудрявая шерсть'), ('scar', 'Шрам'), ('collar', 'Ошейник'), ('none', 'Нет особых примет')], default='none', max_length=20, verbose_name='Особые приметы'),
        ),
    ]
