# Generated by Django 4.2 on 2025-05-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_advertisement_ai_analyzed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='special_features',
            field=models.CharField(choices=[('heterochromia', 'Гетерохромия'), ('ear_fold', 'Залом на ухе'), ('eye_spot', 'Пятно на глазу'), ('missing_eye', 'Нет глазика'), ('tail_missing', 'Отсутствует хвост'), ('limb_missing', 'Отсутствует лапка'), ('albino', 'Альбинизм'), ('vitiligo', 'Витилиго'), ('spotted_pattern', 'Пятнистый узор'), ('striped_pattern', 'Полосатый узор'), ('fluffy_coat', 'Пушистая шерсть'), ('curly_coat', 'Кудрявая шерсть'), ('scar', 'Шрам'), ('collar', 'Ошейник'), ('none', 'Нет особых примет')], default='none', max_length=20, verbose_name='Особые приметы'),
        ),
    ]
